# Generated by Django 4.1.7 on 2023-02-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='title',
            new_name='product',
        ),
    ]
